# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='pageContent',
            new_name='page_content',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='pageTitle',
            new_name='page_title',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='showOnHomepage',
            new_name='show_on_homepage',
        ),
        migrations.RemoveField(
            model_name='page',
            name='pageURL',
        ),
        migrations.AddField(
            model_name='page',
            name='page_url',
            field=models.CharField(default='pageURL', max_length=50, unique=True, validators=[pages.models.validate_url], verbose_name='Page URL (http://kvrx.org/PAGEURL)'),
            preserve_default=False,
        ),
    ]
