# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='showDate',
            new_name='show_date',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='showname',
            new_name='show_name',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='startTime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='albumID',
            new_name='album_ID',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='txArtist',
            new_name='tx_artist',
        ),
        migrations.AddField(
            model_name='song',
            name='current_track',
            field=models.BooleanField(default=False, verbose_name='Current track?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deejay',
            name='dj',
            field=models.CharField(max_length=50, unique=True, verbose_name='DJ Name'),
        ),
        migrations.AlterField(
            model_name='deejay',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date',
            field=models.DateField(verbose_name='Playlist date'),
        ),
        migrations.AlterField(
            model_name='show',
            name='dj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.Deejay', verbose_name='DJ'),
        ),
    ]
